[tool.poetry]
name = "rabbit-demo"
version = "0.1.0"
description = "demo"
authors = ["Your Name <you@example.com>"]
license = "mit"
package-mode = false


[tool.poetry.dependencies]
python = "3.11.8"
pika = "*"


[build-system]

requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
